Monster spawn
lafreak/bango-sdk pull request #12
Opened 2022-10-25 10:40 UTC by Cr3ativeZen

2022-10-29 14:25 UTC, lafreak commented on apps/gameserver/include/Character.h
> +    static id_t g_max_id;
This should not be public. ID generation should be hidden inside Character class and not exposed to other classes.

2022-10-29 14:26 UTC, lafreak commented on apps/gameserver/include/Character.h
> +    static id_t g_max_id;
To achieve it, I suggest creating new public method: `AssignNewId` which in future will be threadsafe (my task) and will be used inside Character constructor and spawner.

2022-10-29 14:29 UTC, lafreak commented on apps/gameserver/include/Monster.h
> +    void PrepareMonsterToSpawn(int new_x, int new_y, int map);
```suggestion
    void Respawn(int new_x, int new_y, int map);
```

2022-10-29 14:32 UTC, lafreak commented on apps/gameserver/include/Spawn.h
> +    std::uint32_t MonsterIndex = 0, Map = 0, Index = 0, Amount = 0, SpawnCycle = 0;
```suggestion
    std::uint32_t MonsterIndex = 0, Map = 0, Area= 0, Amount = 0, SpawnCycle = 0;
```
Why not call it as it is inside config file?

2022-10-29 14:36 UTC, lafreak commented on apps/gameserver/include/World.h
> +    typedef std::unordered_map<Character::id_t, std::shared_ptr<Spawn>>     SpawnContainer;
Is there any reason why we should keep it inside a map?
I don't think we will ever need to identify spawn by id.
It does not inherit from Character.
Could it be std::list or any container which is not key value?

2022-10-29 14:37 UTC, lafreak commented on apps/gameserver/include/World.h
> +    static void SpawnGenMonster();
```suggestion
    static void SpawnMonsters();
```

2022-10-29 14:38 UTC, lafreak commented on apps/gameserver/include/World.h
> +        Get().m_spawns.clear();
Here we remove monsters before we remove spawns. Is it safe? Will spawner keep respawning monsters because monsters got deleted? What is the expected behavior here?

2022-10-29 14:41 UTC, lafreak commented on apps/gameserver/src/Monster.cpp
> +    m_id = Character::g_max_id++;
Why moved declaration out of this function? I think we should minimize access to that variable and only have access to it here.

2022-10-29 14:42 UTC, lafreak commented on apps/gameserver/src/Monster.cpp
> +void Monster::PrepareMonsterToSpawn(int new_x, int new_y, int map)
```suggestion
void Monster::RestoreInitialState(int new_x, int new_y, int map)
```

2022-10-29 14:42 UTC, lafreak commented on apps/gameserver/src/Monster.cpp
> +void Monster::PrepareMonsterToSpawn(int new_x, int new_y, int map)
Why is `int map` here?

2022-10-29 14:42 UTC, lafreak commented on apps/gameserver/src/RegularMonster.cpp
> +    SetDeathTime(bango::utils::time::now());
Why do RegularMonsters need to have death time set?

2022-10-29 14:51 UTC, lafreak commented on apps/gameserver/src/Spawn.cpp
> +        auto monster_lock = monster->Lock();
Here you lock because you want to check if monster is ready to be respawned (CGS_KO).
I don't think you really need to lock.

In the context of monster _just_ got killed and you ask too quick for CGS_KO, its not a problem. We will not respawn but the next tick iteration will respawn it, right? We can live with that.

In the context of we checking CGS_KO and we are afraid that when we perform respawn some other thread will change state (remove CGS_KO) - can it really happen? I think the only thread that can remove CGS_KO should be this tick thread during respawn. Other thread should NEVER do that, right?

We need to ensure no other thread edits monster during respawn. How to do that?
Which other threads can edit? Player recv packets. For example player->monster attack.
If we ensure that monster is already CGS_KO during attack packet we SHOULD reject attack. This will ensure us that nothing can write to it beside spawner.

To summarize, CGS_KO can be our safe flag that there is only one thread that can edit monster - Ticker.

2022-10-29 14:57 UTC, lafreak commented on apps/gameserver/src/Spawn.cpp
> +        switch (init_monster->Race)
This switch duplicates switch inside Monster::Summon. This is not maintainable in the long run - what if we add 5 more monster kinds - do we want to remember to add to support all types in both places. I dont think we need to.

My suggestion is to separate the Monster builder method and spawn method.

Monster::CreateMonster could be the builder and create monster based on init,x,y,map. Create but not add to the world. We could have the switch in there.

Other logic should be separated and re-use Monster::CreateMonster.

Here we could call Monster::CreateMonster, check if it is not nullptr (error during creation) and insert into the world and spawner container.
Other place (on demand Summon - /mob or boss spawn) could also reuse Monster::CreateMonster and add to the world in separate Monster::Summon method.

2022-10-29 15:04 UTC, lafreak commented on apps/gameserver/src/World.cpp
> +        auto new_spawn = std::make_shared<Spawn>(GenMonster::DB().at(init.second->Index));
Here we iterate over GenMonster entries (`init` variable containing key and value pair (`area` and `GenMonster` ptr)).
For each entry, we retrieve the area (`init.second->Index`) and use it to get ` GenMonster` ptr. Why? We already have the ptr inside `init` variable. `init.second` is the pointer.

2022-10-29 15:05 UTC, lafreak commented on apps/gameserver/src/World.cpp
> +    std::lock_guard<std::recursive_mutex> lock(Get().m_entities_rmtx);
We currently do not need to lock. The container does not change in runtime.
It will probably change if we add hot reload at runtime (inix supports that?)

2022-10-29 20:55 UTC, Cr3ativeZen commented on apps/gameserver/include/Character.h
> +    static id_t g_max_id;
done

2022-10-29 20:59 UTC, Cr3ativeZen commented on apps/gameserver/include/Spawn.h
> +    std::uint32_t MonsterIndex = 0, Map = 0, Index = 0, Amount = 0, SpawnCycle = 0;
done

2022-10-29 21:11 UTC, Cr3ativeZen commented on apps/gameserver/src/World.cpp
> +        auto new_spawn = std::make_shared<Spawn>(GenMonster::DB().at(init.second->Index));
ups, done

2022-10-29 21:11 UTC, Cr3ativeZen commented on apps/gameserver/include/World.h
> +    typedef std::unordered_map<Character::id_t, std::shared_ptr<Spawn>>     SpawnContainer;
done

2022-10-29 21:12 UTC, Cr3ativeZen commented on apps/gameserver/include/World.h
> +    static void SpawnGenMonster();
done

2022-10-29 21:12 UTC, Cr3ativeZen commented on apps/gameserver/src/Monster.cpp
> +    m_id = Character::g_max_id++;
done

2022-10-29 21:14 UTC, Cr3ativeZen commented on apps/gameserver/src/Monster.cpp
> +void Monster::PrepareMonsterToSpawn(int new_x, int new_y, int map)
done

2022-10-29 21:23 UTC, Cr3ativeZen commented on apps/gameserver/src/World.cpp
> +    std::lock_guard<std::recursive_mutex> lock(Get().m_entities_rmtx);
Inix does not support that i think, but it's an useful feature and we should have it later on. I will remove lock_guard for now.

2022-10-29 21:23 UTC, Cr3ativeZen commented on apps/gameserver/src/RegularMonster.cpp
> +    SetDeathTime(bango::utils::time::now());
done

2022-10-29 21:24 UTC, Cr3ativeZen commented on core/processor/include/bango/processor/db.h
>  #include <functional>
ups, done

2022-10-29 21:30 UTC, Cr3ativeZen commented on apps/gameserver/src/Spawn.cpp
> +        auto monster_lock = monster->Lock();
reload at spawn time might be an issue later on.
i will remove lock for now

2022-10-29 21:53 UTC, Cr3ativeZen commented on apps/gameserver/include/World.h
> +        Get().m_spawns.clear();
It might be a case, and mob could get added via World::Add back to m_monsters.

2022-10-30 11:38 UTC, Cr3ativeZen commented on apps/gameserver/src/Spawn.cpp
> +        switch (init_monster->Race)
done

2022-10-31 00:28 UTC, lafreak commented on apps/gameserver/src/Monster.cpp
> +    World::Add(Monster::CreateMonster(index, x, y, map));
Error handling is missing - CreateMonster can return nullptr

2022-10-31 11:16 UTC, lafreak commented on apps/gameserver/include/Character.h
> +    void AssignNewId();
Could this be protected? So Monster class can use it but no other classes can.

2022-10-31 11:18 UTC, lafreak commented on apps/gameserver/include/World.h
> +    static void SpawnMonster();
```suggestion
    static void SpawnMonsters();
```

2022-10-31 11:28 UTC, lafreak commented on apps/gameserver/src/Spawn.cpp
> +        if(monster->IsGState(CGS_KO))
Add note here that we have thread-safety by making sure we always call RemoveDeadMonsters and Spawn::Tick in the same thread and that Spawn::Tick is called **after** RemoveDeadMonsters.

2022-10-31 11:29 UTC, lafreak commented on apps/gameserver/src/Spawn.cpp
> +    World::Add(monster);
World add/remove API is missing check if the monster with given ID already exist. It's not an issue here but in the future it will be important to catch bugs early. Add TODO.

2022-10-31 11:30 UTC, lafreak commented on apps/gameserver/include/Spawn.h
> +    void RespawnOnWorld(std::shared_ptr<Monster> monster);
This can be const

2022-10-31 11:32 UTC, lafreak commented on apps/gameserver/src/Spawn.cpp
> +        if(monster->IsGState(CGS_KO))
This call can crash if we end up in line 72.

```

    for (int i = 0; i < GetAmount(); i++)
    {
        auto monster = Monster::CreateMonster(GetMonsterIndex(), GetRandomX(), GetRandomY(), GetMap());
        if(!monster)
            spdlog::error("Monster was not created correctly.");
        m_area_monsters.at(i) = monster;  // HERE WE POSSIBLY PUT nullptr
        World::Add(monster);
    }
```

and when we put that nullptr and we iterate over vector here in tick we will dereference nullptr.

2022-10-31 11:36 UTC, lafreak commented on apps/gameserver/src/Spawn.cpp
> +        auto monster = Monster::CreateMonster(GetMonsterIndex(), GetRandomX(), GetRandomY(), GetMap());
As far I see the transaction policy for CreateMonster method is that we always return valid ptr. The only exit from this function is by throwing an exception. We should use that and catch that exception instead of calling `if(!monster)`

2022-10-31 11:37 UTC, lafreak commented on apps/gameserver/src/Spawn.cpp
> +        auto monster = Monster::CreateMonster(GetMonsterIndex(), GetRandomX(), GetRandomY(), GetMap());
We should not add into the list if the exception happen

2022-10-31 11:37 UTC, lafreak commented on apps/gameserver/src/Spawn.cpp
> +        auto monster = Monster::CreateMonster(GetMonsterIndex(), GetRandomX(), GetRandomY(), GetMap());
We also should not add nullptr to the world

2022-10-31 11:42 UTC, lafreak commented on apps/gameserver/include/World.h
> +    static void SpawnMonster();
Even SpawnMonsters is misleading in this case.
This is responsible for two things:
- creating spawns (the containers)
- spawns monsters related to those spawns

My final suggestion is: `CreateSpawns`

2022-10-31 11:47 UTC, lafreak commented on apps/gameserver/include/World.h
> +    static void SpawnMonster();
Or even better: `CreateSpawnsAndSpawnMonsters`

2022-10-31 11:49 UTC, lafreak commented on apps/gameserver/src/Spawn.cpp
> +        spdlog::error("Monster ID does not exist in InitMonster {}", GetMonsterIndex()); // TODO: object shouldn't be created.
This can easily be done in World::CreateSpawnsAndSpawnMonsters method.

```
void World::CreateSpawnsAndSpawnMonsters()
{
    for(const auto& init : GenMonster::DB())
    {
        if (InitMonster::DB().count(init.second->MonsterIndex) == 0)
        {
             log error;
             continue;
         }
        Get().m_spawns.emplace_back(std::make_shared<Spawn>(init.second));
    }
}
```

2022-10-31 11:50 UTC, lafreak commented on apps/gameserver/src/Spawn.cpp
> +        spdlog::error("Monster ID does not exist in InitMonster {}", GetMonsterIndex()); // TODO: object shouldn't be created.
Then we can get rid of the if in line 18.

2022-10-31 11:53 UTC, lafreak requested changes
You are 5 commits away from master. Please rebase your changes.

2022-10-31 12:57 UTC, Cr3ativeZen commented on apps/gameserver/include/World.h
> +    static void SpawnMonster();
done

2022-10-31 12:57 UTC, Cr3ativeZen commented on apps/gameserver/include/Character.h
> +    void AssignNewId();
done

2022-10-31 12:59 UTC, Cr3ativeZen commented on apps/gameserver/src/Spawn.cpp
> +        if(monster->IsGState(CGS_KO))
done

2022-10-31 13:01 UTC, Cr3ativeZen commented on apps/gameserver/src/Spawn.cpp
> +    World::Add(monster);
done

2022-10-31 13:04 UTC, Cr3ativeZen commented on apps/gameserver/include/Spawn.h
> +    void RespawnOnWorld(std::shared_ptr<Monster> monster);
done

2022-10-31 13:18 UTC, Cr3ativeZen commented on apps/gameserver/src/Spawn.cpp
> +        spdlog::error("Monster ID does not exist in InitMonster {}", GetMonsterIndex()); // TODO: object shouldn't be created.
done

2022-10-31 13:43 UTC, Cr3ativeZen commented on apps/gameserver/src/Spawn.cpp
> +        auto monster = Monster::CreateMonster(GetMonsterIndex(), GetRandomX(), GetRandomY(), GetMap());
done

2022-10-31 13:45 UTC, Cr3ativeZen commented on apps/gameserver/src/Spawn.cpp
> +        auto monster = Monster::CreateMonster(GetMonsterIndex(), GetRandomX(), GetRandomY(), GetMap());
done

2022-10-31 13:54 UTC, Cr3ativeZen commented on apps/gameserver/src/Spawn.cpp
> +        if(monster->IsGState(CGS_KO))
try catch added instead, Monster::CreateMonster aka std::make_shared will never return nullptr.

2022-10-31 15:32 UTC, lafreak commented on apps/gameserver/src/Spawn.cpp
> +        auto monster = Monster::CreateMonster(GetMonsterIndex(), GetRandomX(), GetRandomY(), GetMap());
Add proper formatting (add indent inside try block)

Do not use resize and at - you are still able to leave nullptr in the m_area_monsters and then dereference it in Spawn::Tick which is unsafe

2022-10-31 15:33 UTC, lafreak commented on apps/gameserver/src/World.cpp
> +            spdlog::error("Monster ID does not exist in InitMonster {}", init.second->MonsterIndex);
Add spawn id (area) into the log as well for better debugging

2022-10-31 19:23 UTC, Cr3ativeZen commented on apps/gameserver/src/World.cpp
> +            spdlog::error("Monster ID does not exist in InitMonster {}", init.second->MonsterIndex);
done

2022-10-31 19:23 UTC, Cr3ativeZen commented on apps/gameserver/src/Spawn.cpp
> +        auto monster = Monster::CreateMonster(GetMonsterIndex(), GetRandomX(), GetRandomY(), GetMap());
my bad...
done

2022-11-01 10:56 UTC, lafreak approved these changes

2022-11-01 10:57 UTC, merged