Exp distribution
lafreak/bango-sdk pull request #21
Opened 2022-11-06 15:49 UTC by Cr3ativeZen

2022-11-06 17:50 UTC, lafreak requested changes

2022-11-06 17:50 UTC, lafreak commented on apps/gameserver/CMakeLists.txt
> +set (CMAKE_CXX_STANDARD 20)
I think you do not use any cpp20 feature, but cpp17 (for range loop). Do not require higher standard that we actually use.

2022-11-06 17:50 UTC, lafreak commented on apps/gameserver/src/Monster.cpp
> +                std::uint64_t exp = static_cast<double>(damage) / all_hostility * m_init->Exp;
Casting damage which is uint64_t to double can cause precision loss.
https://stackoverflow.com/questions/63093880/divide-two-64-bit-numbers-and-store-the-result-in-a-float-without-losing-precisi

2022-11-06 17:50 UTC, lafreak commented on apps/gameserver/include/Player.h
> +    void CalculateExp(std::uint64_t& exp, std::uint8_t monster_level);
Why passing the reference? Can we return the result instead?

2022-11-06 17:50 UTC, lafreak commented on apps/gameserver/src/Party.cpp
> +            SetTopLevel();
Getters and setters should be prefixed with Get and Set. Here we prefix with Set but in fact this is not a setter (no value is passed as first parameter). I suggest to rename to `UpdateTopLevel`

2022-11-06 17:50 UTC, lafreak commented on apps/gameserver/src/Party.cpp
> +    m_top_level = player->GetLevel() > m_top_level ? player->GetLevel() : m_top_level;
What do you think about calling `UpdateTopLevel` here? I know current implementation is more performance (we do not need to iterate over player list) but we could encapsulate setting top level behavior in one single place. I'm not sure what's better.

2022-11-06 17:50 UTC, lafreak commented on apps/gameserver/src/Player.cpp
We can actually unlock the attacker earlier, when we are sure not to modify or use player's dynamic properties any more.
I think this is line 668, right?

2022-11-06 17:50 UTC, lafreak commented on apps/gameserver/src/Player.cpp
> +        return;
We should inform administrator why the exp is not being added. spdlog warn?

2022-11-06 17:50 UTC, lafreak commented on apps/gameserver/src/Player.cpp
> +    return !IsGState(0x0000023); // check for 3 gstates: CGS_KNEE, CGS_KO, CGS_FISH
0x23 is magic constant here. Use existing enum and combine all 3:
`CGS_KNEE | CGS_KO | CGS_FISH`

2022-11-06 17:50 UTC, lafreak commented on apps/gameserver/src/Player.cpp
> +        if (std::abs(level_difference) >= 20)
you can use `std::min`:
```
level_difference = std::min(std::abs(level_difference), 20);
```

2022-11-06 17:50 UTC, lafreak commented on apps/gameserver/src/Player.cpp
> +        exp = (exp - exp * (g_nReviseExpB[(GetLevel() - 1) / 10][level_difference] / 100.0));
Calculating monster color and applying ratio based on color ratio is in one line here. It is also duplicated in 863. Separate those operations and add coments which step does what. It should help us maintain the calculations.

2022-11-06 18:00 UTC, Cr3ativeZen commented on apps/gameserver/include/Monster.h
> +    void ExpDistribution();
done

2022-11-06 18:03 UTC, Cr3ativeZen commented on apps/gameserver/include/Monster.h
> +    std::uint64_t all_hostility;
I think it's easier to add damage to hostility_map every time monster gets hit because suming all values in hostility_map every monster death might be time consuming when more players hits same mob. Mainsrv has this value aswell.

2022-11-06 18:03 UTC, Cr3ativeZen commented on apps/gameserver/include/Monster.h
> +    std::map<id_t, std::uint64_t> hostility_map;
no we dont, done

2022-11-06 18:04 UTC, Cr3ativeZen commented on apps/gameserver/include/Character.h
> +    virtual void ReceiveDamage(id_t id, std::uint32_t damage);
Only id is needed in this case

2022-11-06 18:05 UTC, Cr3ativeZen commented on apps/gameserver/include/Party.h
> +    static constexpr std::uint16_t EXP_RECEIVE_RANGE = 640;
it is range from monster

2022-11-06 18:06 UTC, Cr3ativeZen commented on apps/gameserver/include/Party.h
> +    static constexpr std::uint16_t EXP_RECEIVE_RANGE = 640;
> Is it range from monster or from party leader? Or party center?
done

2022-11-06 18:06 UTC, Cr3ativeZen commented on apps/gameserver/include/Party.h
> +    static constexpr std::uint16_t EXP_RECEIVE_RANGE = 640;
> Is it range from monster or from party leader? Or party center?

done

2022-11-06 18:07 UTC, Cr3ativeZen commented on apps/gameserver/src/Player.cpp
yes, done

2022-11-06 18:07 UTC, Cr3ativeZen commented on apps/gameserver/src/Player.cpp
> +        return;
done

2022-11-06 18:08 UTC, Cr3ativeZen commented on apps/gameserver/src/Player.cpp
> +    return !IsGState(0x0000023); // check for 3 gstates: CGS_KNEE, CGS_KO, CGS_FISH
done

2022-11-06 18:11 UTC, Cr3ativeZen commented on apps/gameserver/src/Player.cpp
> +        if (std::abs(level_difference) >= 20)
done

2022-11-06 18:21 UTC, Cr3ativeZen commented on apps/gameserver/src/Player.cpp
> +        exp = (exp - exp * (g_nReviseExpB[(GetLevel() - 1) / 10][level_difference] / 100.0));
line 857(g_nReviseExpB) calculates exp when Monster has lower level than player.
line 863(g_nReviseExpA) calculates exp when Monster has higher level than player.
I added some comments

2022-11-06 20:03 UTC, lafreak commented on apps/gameserver/include/Monster.h
> +#include <map>
Not used, include unordered_map

2022-11-06 23:05 UTC, Cr3ativeZen commented on apps/gameserver/CMakeLists.txt
> +set (CMAKE_CXX_STANDARD 20)
done

2022-11-06 23:10 UTC, Cr3ativeZen commented on apps/gameserver/src/Monster.cpp
> +                std::uint64_t exp = static_cast<double>(damage) / all_hostility * m_init->Exp;
done

2022-11-06 23:12 UTC, Cr3ativeZen commented on apps/gameserver/include/Player.h
> +    void CalculateExp(std::uint64_t& exp, std::uint8_t monster_level);
done

2022-11-07 12:28 UTC, Cr3ativeZen commented on apps/gameserver/src/Party.cpp
> +    m_top_level = player->GetLevel() > m_top_level ? player->GetLevel() : m_top_level;
well, since party creation is not used so often we might aswell use UpdateTopLevel here.

2022-11-07 12:28 UTC, Cr3ativeZen commented on apps/gameserver/include/Monster.h
> +#include <map>
ups,done

2022-11-07 12:29 UTC, Cr3ativeZen commented on apps/gameserver/src/Party.cpp
> +            SetTopLevel();
done

2022-11-07 22:29 UTC, lafreak commented on apps/gameserver/src/Player.cpp
>          if(level_difference >= 20)
Use std min here as well. This can be unified to single call before if/else.

2022-11-07 22:35 UTC, lafreak commented on apps/gameserver/src/Monster.cpp
> +                std::uint64_t exp = static_cast<long double>(damage) / total_hostility * m_init->Exp;
To be sure about casting order first calculate share percentage:
```
double exp_share = static_cast<double>(damage) / static_cast<double>(total_hostility);
```
and then use it to get share out of total exp:
```
exp *= exp_share;
```

2022-11-07 22:36 UTC, lafreak commented on apps/gameserver/src/Party.cpp
> +    UpdateTopLevel();
I don't think it will work if you call it before adding player to the list. Have you tested it?

2022-11-07 22:39 UTC, lafreak commented on apps/gameserver/src/Player.cpp
> +#include <algorithm>
Why do we need it?

2022-11-07 22:41 UTC, lafreak commented on apps/gameserver/include/Party.h
> +    static constexpr std::uint16_t EXP_RECEIVE_RANGE = 640;
> it is range from monster

If so, why is it in Party header? It can be misleading

2022-11-08 15:07 UTC, Cr3ativeZen commented on apps/gameserver/src/Monster.cpp
> +                std::uint64_t exp = static_cast<long double>(damage) / total_hostility * m_init->Exp;
done

2022-11-08 15:11 UTC, Cr3ativeZen commented on apps/gameserver/src/Party.cpp
> +    UpdateTopLevel();
yyes it wont work ... ups, done

2022-11-08 15:11 UTC, Cr3ativeZen commented on apps/gameserver/src/Player.cpp
> +#include <algorithm>
we dont, done

2022-11-08 15:18 UTC, Cr3ativeZen commented on apps/gameserver/src/Player.cpp
>          if(level_difference >= 20)
done

2022-11-08 18:20 UTC, lafreak commented on apps/gameserver/src/Player.cpp
> +    std::int32_t level_difference =  monster_level - GetLevel();
This can overflow if monster_level is lower than player level since both are unsigned.

2022-11-08 18:38 UTC, Cr3ativeZen commented on apps/gameserver/src/Player.cpp
> +    std::int32_t level_difference =  monster_level - GetLevel();
done

2022-11-08 19:13 UTC, lafreak submitted a review, later dismissed

2022-11-08 21:38 UTC, lafreak approved these changes

2022-11-08 21:39 UTC, merged